/**
 * P11 — Designer Author Proposal Generation: the first module that ASSEMBLES
 * an `AuthorProposal` from structured input, rather than accepting a
 * caller-supplied `content` string directly (P09's `buildAuthorProposal`
 * still does exactly that — this module sits one layer above it).
 *
 * No LLM. No prompts. No inference. `assembleProposalContent` is a pure,
 * deterministic template over exactly the fields the caller supplied (kind,
 * semanticFamily, parentComponent, designerIntent, evidence) — it never adds
 * a fact the request did not already carry. `designerIntent` is a
 * human-supplied statement, transported verbatim; it is not generated by
 * this module under any circumstance.
 *
 * `validateProposalGenerationRequest` mirrors `brand-kit.ts`'s
 * `parseBrandKit` fail-loud discipline: a malformed request (empty
 * `designerIntent`, empty `semanticFamily`, unattributed `origin`, or a
 * present-but-empty `parentComponent`) throws `ProposalGenerationError`
 * before anything is constructed — never a silently degraded proposal.
 *
 * Isolation is unchanged from P09/P10: this module never imports the
 * catalog/repository/knowledge subsystem, never validates `semanticFamily`
 * or `parentComponent` against real vocabulary (that remains explicitly
 * future/out-of-scope work, per P09 §3), and the one filesystem touchpoint
 * (`generateAndPersistProposalPackage`) delegates entirely to
 * `proposal-io.ts`'s already-proven, already-isolated `writeProposalPackage`
 * — this file itself never imports `node:fs`.
 */
import { buildAuthorProposal, type AuthorProposal, type ProposalEvidence, type ProposalKind, type ProposalOrigin, type ProposalStatus } from './proposal.js';
import { buildProposalPackage, type ProposalPackage } from './proposal-package.js';
import { writeProposalPackage } from './proposal-io.js';
import { buildProposalManifestReport, type ProposalManifestReport } from './proposal-report.js';

export class ProposalGenerationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'ProposalGenerationError';
  }
}

/**
 * The minimum deterministic input Designer Author needs to assemble a
 * proposal: component metadata (kind + semanticFamily + optional
 * parentComponent), designer intent (human-supplied, verbatim), evidence,
 * and author identity (`origin`, reused unchanged from proposal.ts).
 */
export interface ProposalGenerationRequest {
  readonly kind: ProposalKind;
  readonly origin: ProposalOrigin;
  readonly semanticFamily: string;
  readonly parentComponent?: string;
  readonly designerIntent: string;
  readonly evidence?: readonly ProposalEvidence[];
  readonly status?: ProposalStatus;
}

export interface GenerateProposalOptions {
  readonly now?: () => string;
}

function isNonEmptyString(v: unknown): v is string {
  return typeof v === 'string' && v.trim() !== '';
}

/** Fail-loud validation — throws ProposalGenerationError on any malformed request. Never silently degrades. */
export function validateProposalGenerationRequest(request: ProposalGenerationRequest): void {
  if (!isNonEmptyString(request.semanticFamily)) {
    throw new ProposalGenerationError('generateProposal: semanticFamily must be a non-empty string');
  }
  if (!isNonEmptyString(request.designerIntent)) {
    throw new ProposalGenerationError(
      'generateProposal: designerIntent must be a non-empty string — proposal generation never invents intent',
    );
  }
  if (!isNonEmptyString(request.origin?.authoredBy)) {
    throw new ProposalGenerationError(
      'generateProposal: origin.authoredBy must be a non-empty string — every generated proposal must be attributable',
    );
  }
  if (request.parentComponent !== undefined && !isNonEmptyString(request.parentComponent)) {
    throw new ProposalGenerationError('generateProposal: parentComponent, when present, must be a non-empty string');
  }
}

/**
 * Pure, deterministic assembly of a proposal's `content` from exactly the
 * request's own structured fields. No invention: every line traces to a
 * field the caller supplied.
 */
export function assembleProposalContent(request: ProposalGenerationRequest): string {
  const lines: string[] = [];
  lines.push(`# Proposed ${request.kind}: ${request.semanticFamily}`);
  lines.push('');
  lines.push('## Designer Intent');
  lines.push('');
  lines.push(request.designerIntent);
  lines.push('');
  lines.push('## Parent Component');
  lines.push('');
  lines.push(request.parentComponent ?? '_(none — new, standalone proposal)_');
  lines.push('');
  lines.push('## Evidence');
  lines.push('');
  const evidence = request.evidence ?? [];
  if (evidence.length === 0) {
    lines.push('_No evidence supplied._');
  } else {
    for (const e of evidence) {
      lines.push(`- ${e.description}${e.reference !== undefined ? ` (${e.reference})` : ''}`);
    }
  }
  return lines.join('\n');
}

/** Validate, then assemble content, then delegate to buildAuthorProposal (P09) unchanged. */
export function generateProposal(request: ProposalGenerationRequest, opts: GenerateProposalOptions = {}): AuthorProposal {
  validateProposalGenerationRequest(request);
  return buildAuthorProposal(
    {
      kind: request.kind,
      origin: request.origin,
      ...(request.parentComponent !== undefined ? { parentComponent: request.parentComponent } : {}),
      semanticFamily: request.semanticFamily,
      content: assembleProposalContent(request),
      ...(request.evidence !== undefined ? { evidence: request.evidence } : {}),
      ...(request.status !== undefined ? { status: request.status } : {}),
    },
    opts,
  );
}

/** Generate a proposal, then delegate to buildProposalPackage (P09) unchanged. */
export function generateProposalPackage(request: ProposalGenerationRequest, opts: GenerateProposalOptions = {}): ProposalPackage {
  return buildProposalPackage({ proposal: generateProposal(request, opts) }, opts);
}

/**
 * Generate a package and persist it via proposal-io.ts's already-proven,
 * already-isolated writeProposalPackage — no new persistence logic.
 */
export function generateAndPersistProposalPackage(
  request: ProposalGenerationRequest,
  filePath: string,
  opts: GenerateProposalOptions = {},
): ProposalPackage {
  const pkg = generateProposalPackage(request, opts);
  writeProposalPackage(filePath, pkg);
  return pkg;
}

/** Generate a batch of proposals, then delegate to buildProposalManifestReport (P10) unchanged. */
export function generateProposalManifestReport(
  requests: readonly ProposalGenerationRequest[],
  opts: GenerateProposalOptions = {},
): ProposalManifestReport {
  const proposals = requests.map((r) => generateProposal(r, opts));
  return buildProposalManifestReport(proposals, opts);
}
