import {describe,expect,it} from 'vitest';
import {directionPrompt,validateDirection} from '../../src/identity/direction.js';
const references=[{id:'r1',assetPath:'refs/editorial.png',selected:['typography' as const],rejected:['palette' as const],note:'Keep type character, not colors.'}];
const proposal={schemaVersion:1 as const,id:'d1',project:'northline',references,summary:'Editorial',locked:['Existing logo'],observations:[{referenceId:'r1',aspect:'typography' as const,observation:'Large serif headings',interpretation:'Editorial character',uncertainty:'Confirm intended weight'}]};
describe('selective reference direction',()=>{
 it('retains exact choices and notes without mutating inputs',()=>{const before=JSON.stringify(references);const prompt=directionPrompt('northline',references);expect(prompt).toContain('typography');expect(prompt).toContain('palette');expect(prompt).toContain(references[0].note);expect(prompt).toMatch(/inspect|inspection/i);expect(JSON.stringify(references)).toBe(before);expect(validateDirection(proposal)).toEqual([]);});
 it.each(['../private.png','/absolute.png','C:/brand/logo.png','refs\\logo.png','refs/../logo.png','refs/file.png:stream'])('diagnoses unsafe reference path %s',assetPath=>{expect(validateDirection({...proposal,references:[{...references[0],assetPath}]})).not.toEqual([]);});
 it('rejects contradictions, duplicate ids and unknown observation refs',()=>{for(const changed of [{...proposal,references:[{...references[0],rejected:['typography']}]},{...proposal,references:[...references,...references]},{...proposal,observations:[{...proposal.observations[0],referenceId:'missing'}]}])expect(validateDirection(changed as typeof proposal)).not.toEqual([]);});
 it('does not invent missing interpretation or accept rejected qualities',()=>{expect(validateDirection({...proposal,observations:[]})).not.toEqual([]);expect(validateDirection({...proposal,observations:[{...proposal.observations[0],interpretation:''}]})).not.toEqual([]);expect(validateDirection({...proposal,observations:[{...proposal.observations[0],aspect:'palette'}]})).not.toEqual([]);});
 it('validates runtime schema and aspect vocabulary',()=>{for(const bad of [null,{}, {...proposal,schemaVersion:2},{...proposal,references:[{...references[0],selected:['unknown']}] }])expect(validateDirection(bad as typeof proposal)).not.toEqual([]);expect(()=>directionPrompt('northline',[{...references[0],assetPath:'../escape'}])).toThrow();});
});
