import fs from 'node:fs';import {createHash,randomUUID} from 'node:crypto';import {tmpdir} from 'node:os';import {join} from 'node:path';import {afterEach,describe,expect,it,vi} from 'vitest';
import {approveIdentity} from '../../src/identity/identity.js';import {materializeIdentity,readInstalledIdentity} from '../../src/identity/identity-materializer.js';import {buildContext} from '../../src/generate/context.js';import {buildAuthorContract} from '../../src/generate/author-contract.js';import {projectDir} from '../../src/paths.js';
const roots:string[]=[];const root=()=>{const p=fs.mkdtempSync(join(tmpdir(),'offscript-materialize-'));roots.push(p);return p};afterEach(()=>{vi.restoreAllMocks();for(const p of roots.splice(0))fs.rmSync(p,{recursive:true,force:true})});
const draft={schemaVersion:1 as const,brandId:'northline',version:1,directionId:'d1',subject:'Northline',css:':root{--accent:#506342;--paper:#faf9f4;--font-text:Georgia}',voice:'Quiet and precise',assets:[]};const approval={actor:'Fixture user',at:'2026-10-05T04:00:00Z',source:'user' as const};const textIdentity=()=>approveIdentity(draft,approval,()=>new Uint8Array());
function refs(p:string){const r=join(p,'references');fs.mkdirSync(r);fs.writeFileSync(join(r,'brief.md'),'---\nschemaVersion: 1\ntrack: website\nbrand: Northline\none-liner: Organize field notes\naudience: Researchers\n---\nOriginal factual content.');return r;}
describe('recoverable identity materialization',()=>{
 it('preserves copy and installs explicit text identity without fake marks',()=>{const p=root(),r=refs(p),brief=fs.readFileSync(join(r,'brief.md'),'utf8');fs.writeFileSync(join(r,'facts.md'),'Original source');materializeIdentity(textIdentity(),p,r);expect(fs.readFileSync(join(r,'brief.md'),'utf8')).toBe(brief);expect(fs.readFileSync(join(r,'facts.md'),'utf8')).toBe('Original source');expect(fs.readFileSync(join(r,'voice.md'),'utf8')).toBe(draft.voice);expect(fs.existsSync(join(r,'brand-kit.json'))).toBe(false);expect(readInstalledIdentity(r)).toEqual(textIdentity());const contract=JSON.parse(fs.readFileSync(join(r,'brand-contract.json'),'utf8'));expect(contract.decidedBy).toBe('auto');expect(contract.unmappedReason).toBeDefined();});
 it('installs a checked light/dark pair and removes only previously managed marks on text switch',()=>{const p=root(),r=refs(p);const bytes=Buffer.from('<svg xmlns="http://www.w3.org/2000/svg"/>');fs.writeFileSync(join(p,'light.svg'),bytes);fs.writeFileSync(join(p,'dark.svg'),bytes);const hash=createHash('sha256').update(bytes).digest('hex');const marked=approveIdentity({...draft,assets:[{path:'light.svg',role:'logo-light',digest:hash},{path:'dark.svg',role:'logo-dark',digest:hash}]},approval,()=>bytes);materializeIdentity(marked,p,r);expect(JSON.parse(fs.readFileSync(join(r,'brand-kit.json'),'utf8')).logo.lightSurfaceMark).toBe('light.svg');fs.writeFileSync(join(r,'unowned.txt'),'Keep');materializeIdentity(approveIdentity({...draft,version:2},approval,()=>bytes),p,r);expect(fs.existsSync(join(r,'brand-kit.json'))).toBe(false);expect(fs.existsSync(join(r,'light.svg'))).toBe(false);expect(fs.readFileSync(join(r,'unowned.txt'),'utf8')).toBe('Keep');});
 it('rejects missing bytes and unowned conflicts before changing the active identity',()=>{const p=root(),r=refs(p);materializeIdentity(textIdentity(),p,r);const marker=fs.readFileSync(join(r,'.offscript-identity.json'),'utf8');const bytes=Buffer.from('image');const next=approveIdentity({...draft,version:2,assets:[{path:'image.png',role:'image',digest:createHash('sha256').update(bytes).digest('hex')}]},approval,()=>bytes);expect(()=>materializeIdentity(next,p,r)).toThrow();expect(fs.readFileSync(join(r,'.offscript-identity.json'),'utf8')).toBe(marker);const foreign=refs(root());fs.writeFileSync(join(foreign,'voice.md'),'Unowned');expect(()=>materializeIdentity(textIdentity(),p,foreign)).toThrow(/unowned/i);expect(fs.readFileSync(join(foreign,'voice.md'),'utf8')).toBe('Unowned');});
 it('rejects conflicting brand, protected inputs and linked destinations',()=>{const p=root(),r=refs(p);expect(()=>materializeIdentity(approveIdentity({...draft,subject:'Other'},approval,()=>new Uint8Array()),p,r)).toThrow(/brand/i);const bytes=Buffer.from('copy');const collision=approveIdentity({...draft,assets:[{path:'brief.md',role:'image',digest:createHash('sha256').update(bytes).digest('hex')}]},approval,()=>bytes);fs.writeFileSync(join(p,'brief.md'),bytes);expect(()=>materializeIdentity(collision,p,r)).toThrow(/protected/i);const link=join(p,'linked');fs.symlinkSync(root(),link,'junction');expect(()=>materializeIdentity(textIdentity(),p,link)).toThrow(/link/i);});
 it('rolls back an injected install failure and detects edited managed files',()=>{const p=root(),r=refs(p);materializeIdentity(textIdentity(),p,r);const marker=fs.readFileSync(join(r,'.offscript-identity.json'),'utf8');const rename=fs.renameSync;let failed=false;vi.spyOn(fs,'renameSync').mockImplementation((from,to)=>{if(!failed&&String(from).includes('staged')&&String(to)===join(r,'voice.md')){failed=true;throw Error('Injected write failure')}return rename(from,to)});expect(()=>materializeIdentity(approveIdentity({...draft,version:2,voice:'Revised'},approval,()=>new Uint8Array()),p,r)).toThrow('Injected');expect(fs.readFileSync(join(r,'.offscript-identity.json'),'utf8')).toBe(marker);expect(readInstalledIdentity(r)).toEqual(textIdentity());vi.restoreAllMocks();fs.writeFileSync(join(r,'voice.md'),'Manual change');expect(()=>readInstalledIdentity(r)).toThrow();expect(()=>materializeIdentity(textIdentity(),p,r)).toThrow();expect(fs.readFileSync(join(r,'voice.md'),'utf8')).toBe('Manual change');});
 it('existing engine consumers read installed project CSS and voice',()=>{const name='identity-test-'+randomUUID(),p=projectDir(name);fs.mkdirSync(p,{recursive:true});roots.push(p);const r=refs(p);materializeIdentity(textIdentity(),p,r);const context=buildContext(name,'website');expect(context.tokens.customProps.get('--accent')).toBe('#506342');expect(buildAuthorContract(context)).toContain('Quiet and precise');});
});

