import {mkdtempSync,rmSync,readFileSync,writeFileSync,mkdirSync,symlinkSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {afterEach,describe,expect,it} from 'vitest';
import {approveIdentity} from '../../src/identity/identity.js';import {saveIdentity,loadIdentity} from '../../src/identity/identity-store.js';
const roots:string[]=[];const root=()=>{const p=mkdtempSync(join(tmpdir(),'offscript-identity-'));roots.push(p);return p};afterEach(()=>{for(const p of roots.splice(0))rmSync(p,{recursive:true,force:true})});
const draft={schemaVersion:1 as const,brandId:'northline',version:1,directionId:'d1',subject:'Northline',css:':root{--accent:#506342}',voice:'Quiet',assets:[]};const approval={actor:'Fixture user',at:'2026-10-05T04:00:00Z',source:'user' as const};const identity=()=>approveIdentity(draft,approval,()=>new Uint8Array());
describe('immutable identity store',()=>{
 it('reopens identically, permits idempotent save and retains conflicting-version history',()=>{const p=root(),v1=identity();saveIdentity(p,v1);const before=readFileSync(join(p,'northline','1','identity.json'),'utf8');saveIdentity(p,v1);expect(loadIdentity(p,'northline',1)).toEqual(v1);expect(Object.isFrozen(loadIdentity(p,'northline',1))).toBe(true);expect(()=>saveIdentity(p,{...v1,voice:'tamper'})).toThrow();const conflict=approveIdentity({...draft,voice:'Different'},approval,()=>new Uint8Array());expect(()=>saveIdentity(p,conflict)).toThrow();expect(readFileSync(join(p,'northline','1','identity.json'),'utf8')).toBe(before);const v2=approveIdentity({...draft,version:2,voice:'Different'},approval,()=>new Uint8Array());saveIdentity(p,v2);expect(loadIdentity(p,'northline',2)).toEqual(v2);expect(loadIdentity(p,'northline',1)).toEqual(v1);});
 it('rejects malformed JSON, tampered digests and unsafe identifiers',()=>{const p=root(),v=identity();saveIdentity(p,v);const file=join(p,'northline','1','identity.json');writeFileSync(file,'{broken');expect(()=>loadIdentity(p,'northline',1)).toThrow();writeFileSync(file,JSON.stringify({...v,digest:'a'.repeat(64)}));expect(()=>loadIdentity(p,'northline',1)).toThrow();for(const brand of ['../escape','CON','northline/other'])expect(()=>loadIdentity(p,brand,1)).toThrow();expect(()=>loadIdentity(p,'northline',0)).toThrow();});
 it('rejects directory junctions including a linked supplied root',()=>{const p=root(),outside=root();symlinkSync(outside,join(p,'northline'),'junction');expect(()=>saveIdentity(p,identity())).toThrow(/link/i);expect(()=>loadIdentity(p,'northline',1)).toThrow(/link/i);const linked=join(p,'linked');symlinkSync(outside,linked,'junction');expect(()=>saveIdentity(linked,identity())).toThrow(/link/i);});
});
