import {createHash} from 'node:crypto';import {describe,expect,it} from 'vitest';
import {approveIdentity,verifyIdentity} from '../../src/identity/identity.js';
const bytes=Buffer.from('<svg xmlns="http://www.w3.org/2000/svg"/>');const digest=createHash('sha256').update(bytes).digest('hex');
const draft={schemaVersion:1 as const,brandId:'northline',version:1,directionId:'d1',subject:'Northline',css:':root{--accent:#506342}',voice:'Quiet',assets:[{path:'logo.svg',digest,role:'logo-light' as const}]};
const approval={actor:'Hill',at:'2026-10-05T04:00:00Z',source:'user' as const};
describe('identity approval snapshot',()=>{
 it('verifies bytes and detects changes to content or approval',()=>{const identity=approveIdentity(draft,approval,()=>bytes);expect(verifyIdentity(identity,()=>bytes)).toBe(true);expect(verifyIdentity(identity,()=>Buffer.from('changed'))).toBe(false);for(const changed of [{...identity,css:'Changed'},{...identity,voice:'Loud'},{...identity,approval:{...approval,actor:'Other'}}])expect(verifyIdentity(changed,()=>bytes)).toBe(false);expect(verifyIdentity(identity,()=>{throw Error('missing')})).toBe(false);});
 it('deep freezes a copy and leaves the draft unchanged',()=>{const before=JSON.stringify(draft);const identity=approveIdentity(draft,approval,()=>bytes);expect(identity.assets).not.toBe(draft.assets);expect(Object.isFrozen(identity)).toBe(true);expect(Object.isFrozen(identity.assets[0])).toBe(true);expect(JSON.stringify(draft)).toBe(before);});
 it('accepts explicit text identity with no logo assets',()=>{expect(verifyIdentity(approveIdentity({...draft,assets:[]},approval,()=>bytes),()=>bytes)).toBe(true);});
 it.each([0,-1,1.5])('rejects invalid version %s',version=>{expect(()=>approveIdentity({...draft,version},approval,()=>bytes)).toThrow();});
 it('rejects missing subject/css/voice, malformed approval and unknown fields',()=>{for(const changed of [{...draft,subject:''},{...draft,css:''},{...draft,voice:''},{...draft,extra:'not schema'}])expect(()=>approveIdentity(changed,approval,()=>bytes)).toThrow();for(const changed of [{...approval,actor:''},{...approval,at:'yesterday'},{...approval,source:'model'}])expect(()=>approveIdentity(draft,changed as typeof approval,()=>bytes)).toThrow();});
 it('rejects traversal, duplicate paths, unknown role and wrong supplied asset hash',()=>{for(const assets of [[{...draft.assets[0],path:'../logo.svg'}],[...draft.assets,...draft.assets],[{...draft.assets[0],role:'unknown'}],[{...draft.assets[0],digest:'a'.repeat(64)}]])expect(()=>approveIdentity({...draft,assets} as typeof draft,approval,()=>bytes)).toThrow();});
 it('checks supplied brand contracts using the existing parser',()=>{expect(()=>approveIdentity({...draft,brandContractJson:'{}'},approval,()=>bytes)).toThrow();const contract=JSON.stringify({schemaVersion:1,subject:'Northline',generatedAt:approval.at,decidedBy:'human',slots:{'--accent':{token:'--accent',confidence:'human'}}});expect(verifyIdentity(approveIdentity({...draft,brandContractJson:contract},approval,()=>bytes),()=>bytes)).toBe(true);});
});
