/**
 * F6 — Next.js Generator (MVP): the first concrete `ProjectGenerator` (F5), targeting Next.js App
 * Router. Entirely in memory — no filesystem writes, no npm, no execution. Content is a
 * deliberate, minimal placeholder (STOP: "Do not attempt full visual fidelity... Do not generate
 * React components beyond minimal placeholders") — the goal is proving the `ProjectGenerator`
 * contract with a real, concrete framework, not shipping production output.
 *
 * Uses ONLY `ProjectModel` data (`docs/fullstack/F6-NEXTJS-GENERATOR.md` §3 for the full
 * ownership grounding):
 *   - `ProjectModel.metadata` → `app/layout.tsx`'s exported `metadata` object.
 *   - `ProjectModel.tokens` (role NAMES only, no values) → a comment in `app/globals.css`.
 *   - `ProjectModel.pages[].view` (the `ViewNode` tree) → `app/page.tsx` / `app/<id>/page.tsx`
 *     placeholder markup: `componentRef`/`id` as data attributes, a slot's own `content` string
 *     (verbatim `PlanItem.content`, never HTML) rendered as plain text.
 *   - `ProjectModel.manifest.client` → the generated `package.json`'s `name`.
 * Never reads or inspects any HTML anywhere in this file.
 */
import type { ProjectModel, ProjectPage, ViewNode } from './project-model.js';
import type {
  ProjectGenerator,
  GeneratedArtifact,
  GeneratedArtifactKind,
  GeneratorDiagnostic,
  GeneratorManifest,
} from './project-generator.js';
import { canonicalizeStructural, versionedStructuralDigest } from '../canonical-digest.js';

// -- canonicalization + digest -- shared with every sibling program via canonical-digest.ts --

const NEXTJS_GENERATOR_VERSION_TAG = 'f6-nextjs-generator@1';

function digestOf(value: unknown): string {
  return versionedStructuralDigest(value, NEXTJS_GENERATOR_VERSION_TAG);
}

function parentDir(path: string): string | undefined {
  const idx = path.lastIndexOf('/');
  return idx > 0 ? path.slice(0, idx) : undefined;
}

function derivedDirectories(files: readonly GeneratedArtifact[]): string[] {
  const dirs = new Set<string>();
  for (const f of files) {
    const d = parentDir(f.path);
    if (d) dirs.add(d);
  }
  return [...dirs].sort();
}

// ── content builders — pure functions of ProjectModel data, nothing invented ───────────────────

function renderViewNode(node: ViewNode): string {
  const tag = node.kind === 'section' ? 'section' : 'div';
  const attrs = `data-component-ref={${JSON.stringify(node.componentRef)}} data-node-id={${JSON.stringify(node.id)}}`;
  const content = (node.props as { content?: unknown }).content;
  const textLine = typeof content === 'string' && content.length > 0 ? `\n        <p>{${JSON.stringify(content)}}</p>` : '';
  const children = node.children.map(renderViewNode).join('');
  return `\n      <${tag} ${attrs}>${textLine}${children}\n      </${tag}>`;
}

function pageComponent(page: ProjectPage): string {
  const body = page.view.map(renderViewNode).join('');
  return [
    `export default function Page() {`,
    `  return (`,
    `    <main data-page-id={${JSON.stringify(page.id)}} data-page-role={${JSON.stringify(page.role)}}>${body}`,
    `    </main>`,
    `  );`,
    `}`,
    '',
  ].join('\n');
}

function pageRoutePath(page: ProjectPage, index: number): string {
  return index === 0 ? 'app/page.tsx' : `app/${page.id}/page.tsx`;
}

function layoutComponent(model: ProjectModel): string {
  return [
    `import type { Metadata } from 'next';`,
    `import './globals.css';`,
    ``,
    `export const metadata: Metadata = {`,
    `  title: ${JSON.stringify(model.metadata.title ?? '')},`,
    `  description: ${JSON.stringify(model.metadata.description ?? '')},`,
    `};`,
    ``,
    `export default function RootLayout({ children }: { children: React.ReactNode }) {`,
    `  return (`,
    `    <html lang="en">`,
    `      <body>{children}</body>`,
    `    </html>`,
    `  );`,
    `}`,
    '',
  ].join('\n');
}

function globalsCss(model: ProjectModel): string {
  const tokenComment = model.tokens.length > 0 ? `/* referenced token roles: ${model.tokens.join(', ')} */\n` : '';
  return [
    `/* generated by createNextJsGenerator — placeholder styles; ProjectModel carries token`,
    ` * ROLE NAMES only (no resolved values), so no real theme is emitted yet. */`,
    tokenComment,
    `* { box-sizing: border-box; }`,
    `body { margin: 0; }`,
    '',
  ].join('\n');
}

function packageJson(model: ProjectModel): string {
  const name = model.manifest.client.toLowerCase().replace(/[^a-z0-9-]+/g, '-') || 'offscript-app';
  const pkg = {
    name,
    version: '0.1.0',
    private: true,
    scripts: { dev: 'next dev', build: 'next build', start: 'next start' },
    dependencies: { next: '^15.0.0', react: '^19.0.0', 'react-dom': '^19.0.0' },
    devDependencies: { typescript: '^5.0.0', '@types/node': '^20.0.0', '@types/react': '^19.0.0' },
  };
  return `${JSON.stringify(canonicalizeStructural(pkg), null, 2)}\n`;
}

const NEXT_CONFIG_CONTENT = `import type { NextConfig } from 'next';\n\nconst nextConfig: NextConfig = {};\n\nexport default nextConfig;\n`;

const TSCONFIG_CONTENT = `${JSON.stringify(
  canonicalizeStructural({
    compilerOptions: {
      target: 'ES2017',
      lib: ['dom', 'dom.iterable', 'esnext'],
      allowJs: true,
      skipLibCheck: true,
      strict: true,
      noEmit: true,
      esModuleInterop: true,
      module: 'esnext',
      moduleResolution: 'bundler',
      resolveJsonModule: true,
      isolatedModules: true,
      jsx: 'preserve',
      incremental: true,
      plugins: [{ name: 'next' }],
      paths: { '@/*': ['./*'] },
    },
    include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
    exclude: ['node_modules'],
  }),
  null,
  2,
)}\n`;

function readme(model: ProjectModel): string {
  return [
    `# ${model.metadata.title ?? model.manifest.client}`,
    '',
    model.metadata.description ?? '',
    '',
    '`createNextJsGenerator` (Offscript Program F, F6) — an in-memory MVP scaffold. Placeholder',
    'implementation: proves the ProjectGenerator contract, not visual fidelity.',
    '',
    `- Pages: ${model.pages.length}`,
    `- Component references: ${model.componentRefs.join(', ')}`,
    `- Source RenderingIR digest: ${model.manifest.sourceDigest}`,
    '',
  ].join('\n');
}

// ── the generator ────────────────────────────────────────────────────────────────────────────

function artifact(path: string, kind: GeneratedArtifactKind, content: string): GeneratedArtifact {
  return { path, kind, content, digest: digestOf(content) };
}

/**
 * The MVP artifact set — the minimum files a Next.js App Router project needs to be recognizable
 * as one: `package.json`, `next.config.ts`, `tsconfig.json`, `app/layout.tsx`,
 * `app/globals.css`, one `app/page.tsx` per `ProjectModel` page (the first maps to the root
 * route; every other page gets its own `app/<id>/page.tsx` segment — a routing decision this
 * generator owns, since `ProjectModel` carries no URL/slug data to route on), and `README.md`.
 */
export function createNextJsGenerator(name = 'nextjs-app-router'): ProjectGenerator {
  return {
    name,
    generate(model, ctx) {
      const diagnostics: GeneratorDiagnostic[] = [];
      const files: GeneratedArtifact[] = [
        artifact('package.json', 'config', packageJson(model)),
        artifact('next.config.ts', 'config', NEXT_CONFIG_CONTENT),
        artifact('tsconfig.json', 'config', TSCONFIG_CONTENT),
        artifact('app/layout.tsx', 'component', layoutComponent(model)),
        artifact('app/globals.css', 'style', globalsCss(model)),
      ];

      if (model.pages.length === 0) {
        diagnostics.push({ level: 'warning', message: 'ProjectModel has zero pages — no app/page.tsx generated.' });
      } else {
        model.pages.forEach((page, index) => {
          files.push(artifact(pageRoutePath(page, index), 'component', pageComponent(page)));
        });
      }

      files.push(artifact('README.md', 'doc', readme(model)));

      if (model.assets.length === 0) {
        diagnostics.push({ level: 'info', message: 'ProjectModel.assets is empty — no public/ assets generated.' });
      }

      const sorted = [...files].sort((a, b) => a.path.localeCompare(b.path));
      const directories = derivedDirectories(sorted);
      const manifest: GeneratorManifest = {
        generator: ctx.generatorName,
        sourceModelDigest: model.digest,
        fileCount: sorted.length,
        directoryCount: directories.length,
        diagnosticCount: diagnostics.length,
      };
      const core = { files: sorted, directories, diagnostics, manifest };
      return Object.freeze({ ...core, digest: digestOf(core) });
    },
  };
}
