import fs from 'node:fs';import {join,relative,resolve} from 'node:path';import {createHash,randomUUID} from 'node:crypto';import {afterEach,describe,expect,it} from 'vitest';
import {emptyContext} from '../../src/project/project-context.js';import {newSession,applySession} from '../../src/project/context-updater.js';import {planWorkflow} from '../../src/project/workflow-planner.js';import {evaluateReadiness} from '../../src/project/readiness-evaluator.js';import {ruleReadinessPolicy} from '../../src/project/readiness-policy.js';import {initProject} from '../../src/project/workspace.js';import {recordProjectSession,loadProjectContext} from '../../src/project/context-store.js';import {writeProjectReadiness} from '../../src/project/readiness-store.js';import {readRuntimeProjectReadiness} from '../../src/project/identity-readiness-adapter.js';import {approveIdentity} from '../../src/identity/identity.js';import {recordIdentityApproval} from '../../src/identity/identity-approval.js';import {materializeIdentity} from '../../src/identity/identity-materializer.js';import {projectDir,repoRoot} from '../../src/paths.js';import type {CreativeStrategy} from '../../src/project/creative-strategy.js';
const digest='a'.repeat(64),at='2026-10-05T04:00:00Z';const strategy:CreativeStrategy={projectComplexity:'standard',creativeMaturity:'guided',brandMaturity:'nascent',evidenceCompleteness:1,riskLevel:'low',expectedDeliverables:['website'],requiredStakeholders:[],requiredApprovals:[],unknownCriticalDecisions:[]};
function readiness(mode='text',actor='Fixture user',audience=true){const b=emptyContext({client:'northline',projectType:'website',deliverables:['website']});const decisions:any[]=[{kind:'confirmed',subject:'brand',to:'Northline'},{kind:'confirmed',subject:'tone',to:'Quiet'},{kind:'asset',subject:'colors_and_type.css'},{kind:'approved',subject:'identity',to:{digest,version:1,mode,actor}}];if(audience)decisions.push({kind:'confirmed',subject:'audience',to:'Researchers'});const context=applySession(b,newSession({goal:'Fixture',decisions},b,at));return {projectType:'website',deliverables:['website' as const],strategy,context,workflow:planWorkflow({projectType:'website',deliverables:['website'],strategy,context}),installedIdentity:{digest,verified:true}};}
const roots:string[]=[];afterEach(()=>{for(const p of roots.splice(0)){const rel=relative(join(repoRoot,'projects'),resolve(p));if(!rel||rel.startsWith('..'))throw Error('Unsafe cleanup');fs.rmSync(p,{recursive:true,force:true})}});
describe('text identity changes only the logo requirement',()=>{
 it('admits approved verified text identity while retaining audience/strategy/workflow gates',()=>{const r=readiness();expect(ruleReadinessPolicy().requirements(r).minAssets).not.toContain('logo');expect(evaluateReadiness(r).admission.admitted).toBe(true);expect(evaluateReadiness({...r,installedIdentity:{digest,verified:false}}).blockers.some(b=>b.id==='asset:logo')).toBe(true);expect(evaluateReadiness(readiness('marks')).blockers.some(b=>b.id==='asset:logo')).toBe(true);expect(evaluateReadiness(readiness('text','')).blockers.some(b=>b.id==='asset:logo')).toBe(true);expect(evaluateReadiness(readiness('text','Fixture user',false)).blockers.some(b=>b.id==='evidence:audience')).toBe(true);expect(evaluateReadiness({...r,strategy:{...strategy,requiredApprovals:['Legal']}}).blockers.some(b=>b.category==='approval')).toBe(true);const workflow={...r.workflow,tasks:r.workflow.tasks.map(t=>t.id==='validate-assets'?{...t,status:'ready' as const}:t)};expect(evaluateReadiness({...r,workflow}).blockers.some(b=>b.category==='workflow')).toBe(true);});
 it('records approval only for installed bytes and refreshes stale serialized flags/context at admission',()=>{const name='identity-test-'+randomUUID();initProject({client:name,projectType:'website'});const root=projectDir(name);roots.push(root);const refs=join(root,'references');const identity=approveIdentity({schemaVersion:1,brandId:'northline',version:1,directionId:'d1',subject:'Northline',css:':root{--accent:#506342}',voice:'Quiet',assets:[]},{actor:'Fixture user',at,source:'user'},()=>new Uint8Array());materializeIdentity(identity,root,refs);recordProjectSession(name,{goal:'Fixture facts',decisions:[{kind:'confirmed',subject:'brand',to:'Northline'},{kind:'confirmed',subject:'audience',to:'Researchers'},{kind:'confirmed',subject:'tone',to:'Quiet'}]},at);const context=loadProjectContext(name);writeProjectReadiness(name,{...readiness(),context,installedIdentity:{digest:'f'.repeat(64),verified:true},workflow:planWorkflow({projectType:'website',deliverables:['website'],strategy,context})});const approved=recordIdentityApproval(name,identity,'text',at);expect(approved.decisions.some(d=>d.subject==='identity'&&d.kind==='approved')).toBe(true);const runtime=readRuntimeProjectReadiness(name)!;expect(runtime.installedIdentity?.digest).toBe(identity.digest);expect(evaluateReadiness(runtime).admission.admitted).toBe(true);recordProjectSession(name,{goal:'Reject',decisions:[{kind:'rejected',subject:'identity',to:{digest:identity.digest}}]},at);expect(evaluateReadiness(readRuntimeProjectReadiness(name)!).blockers.some(b=>b.id==='asset:logo')).toBe(true);fs.writeFileSync(join(refs,'voice.md'),'Tampered after approval');expect(()=>readRuntimeProjectReadiness(name)).toThrow();expect(()=>recordIdentityApproval(name,identity,'text',at)).toThrow();});
});

function projectFixture(prefix='identity-test'){
 const name=prefix+'-'+randomUUID();initProject({client:name,projectType:'website'});const root=projectDir(name);roots.push(root);const refs=join(root,'references');
 recordProjectSession(name,{goal:'Fixture facts',decisions:[{kind:'confirmed',subject:'brand',to:'Northline'},{kind:'confirmed',subject:'audience',to:'Researchers'},{kind:'confirmed',subject:'tone',to:'Quiet'}]},at);
 const context=loadProjectContext(name);writeProjectReadiness(name,{...readiness(),context,workflow:planWorkflow({projectType:'website',deliverables:['website'],strategy,context})});
 const identity=approveIdentity({schemaVersion:1,brandId:'northline',version:1,directionId:'d1',subject:'Northline',css:':root{--accent:#506342}',voice:'Quiet',assets:[]},{actor:'Fixture user',at,source:'user'},()=>new Uint8Array());
 return {name,root,refs,identity};
}
it('admits the actual approved marks pair through the existing asset/context contract',()=>{
 const {name,root,refs,identity}=projectFixture();const bytes=Buffer.from('<svg xmlns="http://www.w3.org/2000/svg"/>');for(const file of ['light.svg','dark.svg'])fs.writeFileSync(join(root,file),bytes);
 const {approval,digest:ignored,...draft}=identity;const marked=approveIdentity({...draft,assets:[{path:'light.svg',role:'logo-light',digest:createHash('sha256').update(bytes).digest('hex')},{path:'dark.svg',role:'logo-dark',digest:createHash('sha256').update(bytes).digest('hex')}]},approval,()=>bytes);
 materializeIdentity(marked,root,refs);const context=recordIdentityApproval(name,marked,'marks',at);expect(context.knownAssets).toContain('identity:logo-light:light.svg');expect(context.knownAssets).not.toContain('[object Object]');expect(evaluateReadiness(readRuntimeProjectReadiness(name)!).admission.admitted).toBe(true);
});
it('preserves customized same-ID workflow definitions and pending review gates',()=>{
 const {name,root,refs,identity}=projectFixture();materializeIdentity(identity,root,refs);const context=loadProjectContext(name),base=planWorkflow({projectType:'website',deliverables:['website'],strategy,context});
 const workflow={...base,tasks:base.tasks.map(t=>t.id==='validate-assets'?{...t,owner:'human-reviewer',objective:'Review every asset by hand',status:'ready' as const}:t)};
 writeProjectReadiness(name,{...readiness(),context,workflow});recordIdentityApproval(name,identity,'text',at);const runtime=readRuntimeProjectReadiness(name)!;expect(runtime.workflow).toEqual(workflow);expect(evaluateReadiness(runtime).blockers.some(b=>b.id==='workflow:validate-assets')).toBe(true);
});
it.each(['context.json','readiness.json'])('rejects linked approval destination %s before any target mutation',file=>{
 const {name,root,refs,identity}=projectFixture();materializeIdentity(identity,root,refs);const other=projectFixture();const outside=join(other.root,file),original=fs.readFileSync(outside);fs.unlinkSync(join(root,file));fs.symlinkSync(outside,join(root,file),'file');
 const priorContext=file==='context.json'?undefined:fs.readFileSync(join(root,'context.json'));
 expect(()=>recordIdentityApproval(name,identity,'text',at)).toThrow(/link/i);expect(fs.readFileSync(outside)).toEqual(original);if(priorContext)expect(fs.readFileSync(join(root,'context.json'))).toEqual(priorContext);
});
it('verifies managed identity even without readiness and requires acquisition before generation',()=>{
 const {name,root,refs,identity}=projectFixture();materializeIdentity(identity,root,refs);fs.unlinkSync(join(root,'readiness.json'));expect(()=>readRuntimeProjectReadiness(name)).toThrow(/readiness/i);
 fs.writeFileSync(join(refs,'voice.md'),'Tampered');expect(()=>readRuntimeProjectReadiness(name)).toThrow(/bytes/i);fs.writeFileSync(join(refs,'.offscript-identity.lock'),'Installing');expect(()=>readRuntimeProjectReadiness(name)).toThrow(/installation/i);
});
it('preserves safe mixed-case project names independently of identity ids',()=>{
 const {name,root,refs,identity}=projectFixture('Demo_Client');materializeIdentity(identity,root,refs);expect(()=>recordIdentityApproval(name,identity,'text',at)).not.toThrow();expect(evaluateReadiness(readRuntimeProjectReadiness(name)!).admission.admitted).toBe(true);
});
